apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  {{- $configAuditsEnabled := include "exporter.configAuditReportsEnabled" . | trim -}}
  {{- $trivyEnabled := include "exporter.vulnerabilityReports.trivyEnabled" . | trim -}}
  {{- $kubescapeEnabled := include "exporter.vulnerabilityReports.kubescapeEnabled" . | trim -}}
  {{- $kubescapePolicyReportsEnabled := include "exporter.vulnerabilityReports.kubescapePolicyReportsEnabled" . | trim -}}
  {{- if or (eq $trivyEnabled "true") (eq $configAuditsEnabled "true") }}
  - apiGroups:
      - aquasecurity.github.io
    resources:
      {{- if eq $trivyEnabled "true" }}
      - vulnerabilityreports
      {{- end }}
      {{- if eq $configAuditsEnabled "true" }}
      - configauditreports
      {{- end }}
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  {{- end }}
  {{- if or (eq $kubescapeEnabled "true") (eq $kubescapePolicyReportsEnabled "true") }}
  - apiGroups:
      - spdx.softwarecomposition.kubescape.io
    resources:
      - vulnerabilitymanifests
      {{- if eq $kubescapePolicyReportsEnabled "true" }}
      - vulnerabilitymanifestsummaries
      {{- end }}
    verbs:
      - get
      - list
      - watch
      {{- if eq $kubescapeEnabled "true" }}
      - update
      - patch
      {{- end }}
  {{- end }}
  {{- if eq $kubescapePolicyReportsEnabled "true" }}
  - apiGroups:
      - wgpolicyk8s.io
    resources:
      - policyreports
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  {{- end }}
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name"  . }}
    namespace: {{ include "resource.default.namespace"  . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name"  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name"  . }}
    namespace: {{ include "resource.default.namespace"  . }}
roleRef:
  kind: Role
  name: {{ include "resource.default.name"  . }}
  apiGroup: rbac.authorization.k8s.io
---
{{ if not .Values.global.podSecurityStandards.enforced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "resource.psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name"  . }}
    namespace: {{ include "resource.default.namespace"  . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
