{{ if .Values.image.pull_secret_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret.yaml: |
    service:
      todo:
        structure:
          token: "xyz"
{{- end }}
